language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3.8
  - 2.2.10
env:
  - TESTOPTS=-v
gemfile:
  - Gemfile
before_install:
  - mkdir /tmp/bioruby
  - ruby gemfiles/modify-Gemfile.rb
  - ruby gemfiles/prepare-gemspec.rb
matrix:
  include:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.travis-ruby1.9
      env: TESTOPTS=-v
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.travis-ruby1.9
      env: TESTOPTS=-v
    - rvm: truffleruby
      gemfile: gemfiles/Gemfile.travis-jruby1.9
      env: TESTOPTS=-v
    - rvm: rbx-3.29
      gemfile: gemfiles/Gemfile.travis-rbx
      env: TESTOPTS=-v
    - rvm: jruby
      gemfile: gemfiles/Gemfile.travis-jruby1.9
      env: TMPDIR=/tmp/bioruby TESTOPTS=-v
    - rvm: 2.5
      gemfile: Gemfile
      env: BIORUBY_RAKE_DEFAULT_TASK=gem-test TESTOPTS=-v
    - rvm: jruby
      gemfile: gemfiles/Gemfile.travis-jruby1.9
      env: TMPDIR=/tmp/bioruby BIORUBY_RAKE_DEFAULT_TASK=gem-test TESTOPTS=-v
  allow_failures:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.travis-ruby1.8
      env: TESTOPTS=-v
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.travis-ruby1.9
      env: TESTOPTS=-v
    - rvm: truffleruby
      gemfile: gemfiles/Gemfile.travis-jruby1.9
      env: TESTOPTS=-v
    - rvm: rbx-3.29
      gemfile: gemfiles/Gemfile.travis-rbx
      env: TESTOPTS=-v
    - rvm: jruby
      gemfile: gemfiles/Gemfile.travis-jruby1.9
      env: TMPDIR=/tmp/bioruby TESTOPTS=-v
    - rvm: jruby
      gemfile: gemfiles/Gemfile.travis-jruby1.9
      env: TMPDIR=/tmp/bioruby BIORUBY_RAKE_DEFAULT_TASK=gem-test TESTOPTS=-v

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

#before_install:
# - sudo apt-get update
# - sudo apt-get install libxml2-dev libexpat1-dev

# block build for the branches
branches:
  except:
    - biohackathon2008
    - bioruby-1.4.3

