---
version: "{build}"
branches:
  only:
    - master
clone_depth: 10
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET BUNDLE_GEMFILE=gemfiles/Gemfile.windows
  - bundle install
  - bundle exec rake regemspec
  - bundle exec rake gem
  - bundle exec gem install pkg/bio-*.gem
  - echo gem "bio" >> gemfiles\Gemfile.windows
build: off
before_test:
  - ruby --version
  - gem --version
  - bundle --version
test_script:
  - bundle exec rake gem-test
environment:
  matrix:
    - ruby_version: "23"
    - ruby_version: "23-x64"
    - ruby_version: "24"
    - ruby_version: "24-x64"
    - ruby_version: "25"
    - ruby_version: "25-x64"
